author: Oliver Borchert
author_url: https://github.com/borchero
module: Squid
module_version: "${VERSION}"
output: docs
clean: true
readme: README.md
documentation: examples/*.md
theme: fullwidth
github_url: https://github.com/borchero/Squid
