name: CocoaPods

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: macos-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        -   name: Install CocoaPods
            run: gem install cocoapods
        -   name: Deploy to CocoaPods
            run: |
                set -eo pipefail
                pod lib lint --allow-warnings
                pod trunk push --allow-warnings
            env:
                COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
