name: Documentation

on:
    release:
        types: [published]

jobs:
    generate-docs:
        runs-on: macos-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        -   name: Generate Documentation
            run: sudo gem install jazzy && jazzy
        -   name: Upload Artifacts
            uses: actions/upload-artifact@v1
            with:
                name: docs
                path: docs/
    
    publish-docs:
        runs-on: ubuntu-18.04
        container: 
            image: borchero/cuckoo:0.4.1
        needs: generate-docs
        steps:
        -   name: Download Artifacts
            uses: actions/download-artifact@v1
            with:
                name: docs
        -   name: Upload artifacts
            run: |
                cuckoo publish \
                    --dir docs \
                    --bucket squid.borchero.com \
                    --purge \
                    --aws-cloudfront-distribution E1P6FI3X51PEKW
            env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
