name: Documentation

on:
    release:
        types: [published]

jobs:
    publish:
        runs-on: macos-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        -   name: Generate Documentation
            uses: steven0351/publish-jazzy-docs@v1.1.1
            with:
                personal_access_token: ${{ secrets.ACCESS_TOKEN }}
                config: .jazzy.yml
